### ISSUE TITLE
status does not work

### ISSUE THREAD

**Issue by ghost** [tdulcet/Colab-Autorun-and-Connect#2]
it cannot check

**Comment by tdulcet** [comment]
Do you mean the status in the page action popup does not work for you? It works fine for me:
![image](https://user-images.githubusercontent.com/15305150/206101278-95c41f67-593e-4916-a4c7-bcf697767b5e.png)

I am sorry to hear that it is not working for you, but I would need more information about your issue to determine the problem. A screenshot would likely be very helpful. What browser and version of the add-on are you using? Did you change any of the default options in the add-on?

**Comment by ghost** [comment]
I was sleep derived sorry for not giving any details, I am using latest version of firefox,  ̶I̶ ̶d̶i̶d̶ ̶c̶h̶a̶n̶g̶e̶ ̶s̶o̶m̶e̶t̶h̶i̶n̶g̶ ̶b̶u̶t̶ ̶I̶ ̶f̶o̶r̶g̶o̶t̶ ̶i̶t̶ ̶s̶a̶d̶l̶y̶ okay I found it just increased seconds to wait and delay from 30 to 60 sec, also it does pop up but can not detect the status it says status ?

**Comment by tdulcet** [comment]
OK, the status only works if it is the extension that connected the notebook. I have not figured out a reliable way for an extension to determine if notebooks are already connected/disconnected, so the add-on will just show the status as "Unknown" if you manually connect a notebook. Note that this status is purely for informational purposes, so the add-on should still work as expected regardless of what it shows.

**Comment by ghost** [comment]
oh okay, so when I go to my notebook but do not click to connect button will the ext. automatically connect?

**Comment by tdulcet** [comment]
Yes, it will automatically connect after 60 seconds, if that is what you set for the "Delay" option. This is one of the main purposes of the add-on. 😉

**Comment by ghost** [comment]
oh, it works now sorry for inconvenience

**Comment by ghost** [comment]
@tdulcet ohhh it reconnected but did not continue do execution :( is there any way you know? first run cell wont work  because there are too many

**Comment by tdulcet** [comment]
Adding an option to run all the cells is a [feature I am considering](https://github.com/tdulcet/Colab-Autorun-and-Connect#contributing) for the next version of this add-on. Is that what you are requesting or do you want to run a specific cell?

**Comment by ghost** [comment]
yes yes all one

**Comment by tdulcet** [comment]
OK, I will consider that feature for the next version of the add-on... Pull requests are of course always welcome.
