### ISSUE TITLE
bypass to google drive authenication

### ISSUE THREAD

**Issue by ghost** [tdulcet/Colab-Autorun-and-Connect#4]
when the extension does reconnect each time it wants to get authenicated by google drive, do you know any way to make it automatically?

**Comment by tdulcet** [comment]
Yeah, you would need to use a different method to connect your Google Drive. See this official [video](https://video.twimg.com/tweet_video/EQbtltjVAAA2qTs.mp4) for a walkthrough.  Your Drive storage will then automatically remount each time you run the notebook. Also see step 1 in our [instructions](https://github.com/tdulcet/Distributed-Computing-Scripts/tree/master/google-colab#how-to-use) for two notebooks I maintain for more information.

**Comment by ghost** [comment]
I created new notebook changed its name copied everything in [this ](https://github.com/ArthurFDLR/whisper-youtube/blob/main/whisper_youtube.ipynb) by hand since it has `from google.colab import drive
drive_mount_path = Path("/") / "content" / "drive"
drive.mount(str(drive_mount_path))
drive_mount_path /= "My Drive"
#@markdown ---
drive_path = "Colab Notebooks/Whisper Youtube" #@param {type:"string"}
#@markdown ---
#@markdown **Run this cell again if you change your Google Drive path.**

drive_whisper_path = drive_mount_path / Path(drive_path.lstrip("/"))
drive_whisper_path.mkdir(parents=True, exist_ok=True)` lines I did not click to mount drive button, anyways i executed cells everything was working google colab disconnected after 2 hours, ur extension reconnected to same notebook that I did not touch anything everyth,ng according to your guide, it asked google drive permission again do you have any idea?

**Comment by tdulcet** [comment]
The issue is that `from google.colab import drive` line. You cannot use that if you want it to automatically mount your Drive storage. Instead, you would need to click the "Mount Drive" button and follow our instructions at the above link. Hope that helps...
