### ISSUE TITLE
reCHAPTA handling

### ISSUE THREAD

**Issue by musahi0128** [tdulcet/Colab-Autorun-and-Connect#6]
Hi, thank you for making this software.

I was testing it today. Usually when I start my notebook and run something, it will ask me to complete a reCHAPTA after around 5min or so. That time it was not showing for a while so I left my PC running. I come back to it after 45min-1h later and find the notebook is running, but upon checking this was actually a new session. It means I miss the reCHAPTA.

I can see you haven't handle this particular condition. I am not a programmer. I'm not aware of any software that can bypass reCHAPTA challange but I am sure detecting the pop up should be something doable with js. So I would like to suggest following feature to your software. If reCHAPTA box is detected, notify user via some methodes. What I can think of is notification in the desktop, play sound notification, and uses service like ntfy.sh. With ntfy.sh, user can setup so they will receive the notification on their phone and take care of the reCHAPTA when it appears.

Please let me know if you need more details and if you have anything I can help you with this feature request.

Thanks!

**Comment by tdulcet** [comment]
Thanks for the using the extension and for the feedback.

The reCAPTCHA popup is automatically dismissed when it appears, as it does not seem to be required and this helps prevent the notebooks from prematurely disconnecting. Are you saying that you would like the extension to keep to reCAPTCHA popup instead, so that the user has an opportunity to complete the reCAPTCHA. I suppose I could add an option to support this, which could also show a desktop notification in this case. Is there a reason you would like to do the reCAPTCHAs?

**Comment by musahi0128** [comment]
Thank you for your responses.

What I experienced is if I don't complete the reCHAPTA, the session will be invalidated after like 15-30 minutes and replaced by a new session, so I need to complete the reCHAPTA.

I am testing it right now and so far after completing the reCHAPTA and activating your add-on, the session has been running for 01:34:47 without me looking at the notebook tab. I'll update this comment if I can get it further than my current situation.

edit:
The session is running for its whole 12h lifespan. Great!
I will do another test without solving the reCHAPTHA and opening two tabs with different session for each. Just to be sure about the requirement for the reCHAPTA.

edit:
Confirmed, the session only run for around 1h without solving the reCHAPTA.

> Are you saying that you would like the extension to keep to reCAPTCHA popup instead, so that the user has an opportunity to complete the reCAPTCHA

Yes indeed

> I suppose I could add an option to support this, which could also show a desktop notification in this case.

And here comes my request. I would like to receive a notification on my phone when the reCHAPTA is detected. That way I can take care of it as soon as the pop up appear. This can be done using ntfy.sh service.

Thanks

**Comment by tdulcet** [comment]
Thank you for doing all of this testing. With the CPU only runtime on the free Colab, my sessions typically last 6+ hours without doing any reCAPTCHAs.

I will add an option to the next version of this extension to support not dismissing the reCAPTCHA popups, which will also show a desktop notification. Depending on your OS, there should be an app you could install to synchronize the desktop notifications to your phone, so using an external service should not be necessary. PRs are welcome though if you still want to support this external service. I have not tried this myself, but you might also be interested in installing an add-on that could allegedly automatically complete the reCAPTCHAs, such as this one: https://addons.mozilla.org/firefox/addon/buster-captcha-solver/.

**Comment by tdulcet** [comment]
I added the requested option in https://github.com/tdulcet/Colab-Autorun-and-Connect/commit/2839cbffd6b97256e1695113e3e77a76cca241b1:
![image](https://github.com/tdulcet/Colab-Autorun-and-Connect/assets/15305150/fd4d3f83-fa27-4dfe-aeee-f5cf4798529f)
This will be included in the next version of the add-on. If you want to try it before then, there are instruction in #1 on how to side load the extension. After installing it, just open the options page to disable the new option. Feedback is welcome.
